---
sidebar: sidebar 
permalink: scpivs44_unmount_a_backup.html 
keywords:  
summary: データストア内のファイルにアクセスする必要がなくなった場合は、バックアップをアンマウントできます。 
---
= バックアップをアンマウント
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
データストア内のファイルにアクセスする必要がなくなった場合は、バックアップをアンマウントできます。

VMware vSphere ClientのGUIにマウント済みとして表示されているバックアップがアンマウントのバックアップ画面に表示されない場合は、REST APIを使用する必要があります `/backup/{backup-Id}/cleanup` バインドされていないデータストアをクリーンアップしてから、手順 のアンマウントをもう一度実行してください。

負荷共有ミラー関係が確立されたルートボリュームを含むStorage VM（SVM）にNFSデータストアのバックアップコピーをマウントしようとすると、エラーが発生する場合があります `You may have reached the maximum number of NFS volumes configured in the vCenter. Check the vSphere Client for any error messages.` この問題を回避するには、[*ESX*>*Manage*>*Settings*>*Advance System Settings*]に移動してNFS.MaxVolumesの値を変更し、最大ボリューム数の設定を変更します。最大値は 256 です。

.手順
. VMware vSphere Clientで、ツールバーの*メニュー*をクリックし、ドロップダウンリストから*ストレージ*を選択します。
. 左側のナビゲーションペインで、データストアを右クリックし、ドロップダウンリストから「 * NetApp SnapCenter * 」を選択してから、セカンダリドロップダウンリストから「 Unmount 」を選択します。
+

IMPORTANT: アンマウントするデータストアを間違えないようにしてください。そうしないと、原因が本番環境に与える影響が発生する可能性があります。

. Unmount cloned Datastore * ダイアログボックスで、データストアを選択し、 * Unmount the cloned datastore * チェックボックスをオンにして、 * Unmount * をクリックします。

