---
sidebar: sidebar 
permalink: scpivs44_download_job_logs.html 
keywords:  
summary: ジョブログは、SnapCenter VMware vSphereクライアントのダッシュボードのジョブモニタタブからダウンロードできます。 
---
= ジョブログをダウンロードします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ジョブログは、SnapCenter VMware vSphereクライアントのダッシュボードのジョブモニタタブからダウンロードできます。

VMware vSphere Clientの使用中に予期しない動作が発生した場合は、ログファイルを使用して原因 を特定し、問題を解決できます。


NOTE: 保持ジョブのログのデフォルト値は 30 日で、保持ジョブのデフォルト値は 90 日です。設定した保持期間よりも古いジョブログとジョブは、 6 時間ごとにパージされます。設定を使用できます `jobs/cleanup` REST APIを使用して、ジョブとジョブログの保持期間を変更できます。パージスケジュールは変更できません。

.手順
. vSphereクライアントの左側のナビゲーションペインで、*ダッシュボード*をクリックし、vCenter Serverを選択して、ダッシュボードペインの*ジョブモニタ*タブをクリックします。
. ジョブモニタのタイトルバーでダウンロードアイコンを選択します。
+
場合によっては、右にスクロールしないとアイコンが表示されないことがあります。

+
ジョブをダブルクリックして [ ジョブの詳細 ] ウィンドウにアクセスし、 [ ジョブログのダウンロード ] をクリックすることもできます。



.結果
ジョブログは、 SnapCenter VMware プラグインが導入されている Linux VM ホスト上にあります。デフォルトの場所は、です `/var/log/netapp`。

ジョブログをダウンロードしようとしたときに、エラーメッセージに示されている名前のログファイルが削除されている場合は、次のエラーが発生する可能性があります。 `HTTP ERROR 500 Problem accessing /export-scv-logs`。このエラーを修正するには、という名前のファイルのファイルアクセスステータスと権限をエラーメッセージで確認し、アクセスの問題を修正します。
