---
sidebar: sidebar 
permalink: scpivs44_rest_apis__download_jobs_and_generate_reports.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere REST APIを使用してVMware vSphereクライアントジョブのレポートの生成とログのダウンロードを行うには、VMware vSphereのREST API呼び出しを使用する必要があります。 
---
= REST API を使用してジョブをダウンロードし、レポートを生成できます
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere REST APIを使用してVMware vSphereクライアントジョブのレポートの生成とログのダウンロードを行うには、VMware vSphereのREST API呼び出しを使用する必要があります。

各REST APIに、を追加します `https://<server>:<port>` を使用して完全なエンドポイントを形成します。



== ジョブの詳細情報を取得するには、 Jobs セクションの次の REST API を使用します。

|===
| REST API | コメント 


| `/4.1/jobs` | `Get all jobs` 複数のジョブのジョブ詳細を取得します。要求の範囲を限定するには、などのジョブタイプを指定します `backup`、 `mountBackup`または `restore`。 


| `/4.1/jobs/{id}` | `Get job details` 指定したジョブの詳細情報を取得します。 
|===


== ジョブセクションの次の REST API を使用して、ジョブログをダウンロードします。

|===
| REST API | コメント 


| `/4.1/jobs/{id}/logs` | `getJobLogsById` 指定したジョブのログをダウンロードします。 
|===


== レポートセクションの次の REST API を使用して、レポートを生成します。

|===
| REST API | コメント 


| `4.1/reports/protectedVM` | `Get Protected VM List` 過去7日間に保護されているVMのリストを取得します。 


| `/4.1/reports/
unProtectedVM` | `Get Unprotected VM List` 直近7日間に保護されていないVMのリストを取得します。 
|===