---
sidebar: sidebar 
permalink: scpivs44_how_restore_operations_are_performed.html 
keywords:  
summary: VMFS 環境の場合、 SnapCenter Plug-in for VMware vSphere は、リストア処理を実行するために、 Storage VMotion でクローンおよびマウント処理を使用します。NFS 環境の場合、このプラグインはネイティブの ONTAP Single File SnapRestore （ SFSR ）を使用して、ほとんどのリストア処理を効率よく実行できます。VVOL VM の場合、このプラグインは ONTAP 単一ファイル Snapshot リストアおよび SnapMirror リストアをリストア処理に使用します。 
---
= リストア処理の実行方法
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMFS 環境の場合、 SnapCenter Plug-in for VMware vSphere は、リストア処理を実行するために、 Storage VMotion でクローンおよびマウント処理を使用します。NFS 環境の場合、このプラグインはネイティブの ONTAP Single File SnapRestore （ SFSR ）を使用して、ほとんどのリストア処理を効率よく実行できます。VVOL VM の場合、プラグインは ONTAP Single File Snapshot Restore （ ONTAP SFSR ）と SnapMirror Restore をリストア処理に使用します。次の表に、リストア処理の実行方法を示します。

|===
| リストア処理 | 移動元 | を使用して実行 


| VM および VMDK | プライマリバックアップ | NFS環境：ONTAP Single File SnapRestoreの略
VMFS環境：Storage VMotionを使用したクローン作成とマウント 


| VM および VMDK | セカンダリバックアップ | NFS環境：ONTAP Single File SnapRestoreの略
VMFS環境：Storage VMotionを使用したクローン作成とマウント 


| VM および VMDK が削除された | プライマリバックアップ | NFS環境：ONTAP Single File SnapRestoreの略
VMFS環境：Storage VMotionを使用したクローン作成とマウント 


| VM および VMDK が削除された | セカンダリバックアップ | NFS環境：Storage VMotionを使用してクローンを作成し、マウントします
VMFS環境：Storage VMotionを使用したクローン作成とマウント 


| VM および VMDK | VM と整合性のあるプライマリバックアップ | NFS環境：ONTAP Single File SnapRestoreの略
VMFS環境：Storage VMotionを使用したクローン作成とマウント 


| VM および VMDK | VM と整合性のあるセカンダリバックアップ | NFS環境：Storage VMotionを使用してクローンを作成し、マウントします
VMFS環境：Storage VMotionを使用したクローン作成とマウント 


| VVol VM | crash-consistent プライマリバックアップ | ONTAP ：すべてのプロトコルを対象とした単一ファイルの SnapRestore 


| VVol VM | crash-consistent セカンダリバックアップ | すべてのプロトコルを対象とした ONTAP の SnapMirror リストア 


| FlexGroup VM | プライマリバックアップ  a| 
NFS 環境：
* ONTAP Single File SnapRestore（ONTAPバージョン9.10.1以降を使用している場合
*以前のバージョンのONTAPでは、Storage VMotionを使用してクローンを作成し、マウントします

VMFS 環境： FlexGroup ではサポートされません



| FlexGroup VM | セカンダリバックアップ  a| 
NFS 環境：

* ONTAPバージョン9.10.1以降を使用している場合は、ONTAP SnapMirrorリストアを実行します
* 以前 ONTAP のバージョンの Storage VMotion を使用して、クローン作成とマウントを行います


VMFS 環境： FlexGroup ではサポートされません

|===

NOTE: VVolコンテナのリバランシング後にVVol VMをリストアすることはできません。

ゲストファイルのリストア操作は、 NFS 環境と VMFS 環境の両方で、（ Storage VMotion ではなく）クローン操作とマウント操作を使用して実行されます。


IMPORTANT: リストア処理中にエラーが発生することがあります `Host unresolved volumes is null` または `Exception while calling pre-restore on SCV….Error mounting cloned LUN as datastore…` これは、SnapCenter VMwareプラグインがクローンの再署名を試みたときに発生します。VMware の制限により、 SnapCenter VMware プラグインは高度な ESXi 構成で自動再署名値を制御できません。

を参照してください https://kb.netapp.com/mgmt/SnapCenter/SCV_clone_or_restores_fail_with_error_'Host_Unresolved_volumes_is_null'#["技術情報アーティクル：SCV clone or restores fail with error 'Host Unresolved volumes is Null"^] エラーの詳細については、を参照してください。
